version: '3.8'

services:
  frontend:
    build:
      context: ./
      dockerfile: Frontend/Dockerfile
    ports:
      - 8080:80
    networks:
      - frontend
    depends_on:
      - user-service
  user-service:
    build:
      context: ./
      dockerfile: UserService/Dockerfile
    networks:
      - frontend
      - user-service
    depends_on:
      - user-database
  user-database:
    build:
      context: ./UserService/Database
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - user-service
  job-service:
    build:
      context: ./
      dockerfile: JobService/Dockerfile
    networks:
      - frontend
      - job-service
    depends_on:
      - job-database
  job-database:
    build:
      context: ./JobService/Database
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - job-service
  offer-service:
    build:
      context: ./
      dockerfile: OfferService/Dockerfile
    networks:
      - frontend
      - offer-service
    depends_on:
      - offer-database
  offer-database:
    build:
      context: ./OfferService/Database
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - offer-service
  contract-service:
    build:
      context: ./
      dockerfile: ContractService/Dockerfile
    networks:
      - frontend
      - contract-service
    depends_on:
      - contract-database
  contract-database:
    build:
      context: ./ContractService/Database
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - contract-service
  review-service:
    build:
      context: ./
      dockerfile: ReviewService/Dockerfile
    networks:
      - frontend
      - review-service
    depends_on:
      - review-database
  review-database:
    build:
      context: ./ReviewService/Database
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - review-service

networks:
  frontend:
  user-service:
  job-service:
  offer-service:
  contract-service:
  review-service:
