version: '3.8'

services:
  frontend:
    build:
      context: ./
      dockerfile: Frontend/Dockerfile
    ports:
      - 8080:80
    networks:
      - frontend
    depends_on:
      - user-service
  user-service:
    build:
      context: ./
      dockerfile: UserService/Dockerfile
    networks:
      - frontend
      - user-service
    depends_on:
      - user-database
  user-database:
    build:
      context: ./UserService/Database
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - user-service
  job-service:
    build:
      context: ./
      dockerfile: JobService/Dockerfile
    networks:
      - frontend
      - job-service
    depends_on:
      - job-database
  job-database:
      build:
        context: ./JobService/Database
      command: --default-authentication-plugin=mysql_native_password
      networks:
        - job-service

networks:
  frontend:
  user-service:
  job-service:
