version: '3.8'

services:
  frontend:
    build:
      context: ./
      dockerfile: Frontend/Dockerfile
    ports:
      - 8080:80
    networks:
      - frontend
    depends_on:
      - user-service
  user-service:
    build:
      context: ./
      dockerfile: UserService/Dockerfile
    networks:
      - frontend
      - backend
    depends_on:
      - database
  database:
    build:
      context: ./UserService/Database
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend

networks:
  frontend:
  backend:
