version: '3.8'

services:
  frontend:
    image: ghcr.io/antje12/ba/frontend:latest
    ports:
      - 8080:80
    networks:
      - frontend
    depends_on:
      - user-service
  user-service:
    image: ghcr.io/antje12/ba/user-service:latest
    networks:
      - frontend
      - user-service
    depends_on:
      - user-database
  user-database:
    image: ghcr.io/antje12/ba/user-database:latest
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - user-service
  job-service:
    image: ghcr.io/antje12/ba/job-service:latest
    networks:
      - frontend
      - job-service
    depends_on:
      - job-database
  job-database:
      image: ghcr.io/antje12/ba/job-database:latest
      command: --default-authentication-plugin=mysql_native_password
      networks:
        - job-service

networks:
  frontend:
  user-service:
  job-service:
