version: '3.8'

services:
  frontend:
    image: ghcr.io/antje12/ba/frontend:latest
    ports:
      - 8080:80
    networks:
      - frontend
    depends_on:
      - user-service
  user-service:
    image: ghcr.io/antje12/ba/user-database:latest
    networks:
      - frontend
      - user-service
    depends_on:
      - user-database
  user-database:
    image: ghcr.io/antje12/ba/user-database:latest
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - user-service

networks:
  frontend:
  user-service:
