apiVersion: v1
kind: Service
metadata:
  name: contract-service
spec:
  ports:
    -
      name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: contract-service-pod
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contract-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contract-service-pod
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: contract-service-pod
    spec:
      containers:
        -
          image: "ghcr.io/antje12/ba/contract-service:latest"
          imagePullPolicy: Always
          name: contract-service
          ports:
            -
              containerPort: 80
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
      imagePullSecrets:
        -
          name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: contract-database
spec:
  ports:
    -
      port: 3306
      targetPort: 3306
  selector:
    app: contract-database-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contract-database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contract-database-pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: contract-database-pod
    spec:
      containers:
        -
          args:
            - "--default-authentication-plugin=mysql_native_password"
          image: "ghcr.io/antje12/ba/contract-database:latest"
          name: mysql
          ports:
            -
              containerPort: 3306
          resources:
            limits:
              cpu: 200m
              memory: 600Mi
            requests:
              cpu: 100m
              memory: 400Mi
          volumeMounts:
            -
              mountPath: /var/lib/mysql
              name: contract-persistent-storage
      imagePullSecrets:
        -
          name: regcred
      volumes:
        -
          name: contract-persistent-storage
          persistentVolumeClaim:
            claimName: contract-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: contract-database-pod
  name: contract-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
