apiVersion: v1
kind: Service
metadata:
  name: review-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: review-service-pod
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service-deployment
spec:
  replicas: 1
    minReadySeconds: 5
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
  selector:
    matchLabels:
      app: review-service-pod
  template:
    metadata:
      labels:
        app: review-service-pod
    spec:
      containers:
        - name: review-service
          image: 'ghcr.io/antje12/ba/review-service:latest'
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
      readinessProbe:
        httpGet:
          path: /Get
          port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: review-database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: review-database-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-database-deployment
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: review-database-pod
  template:
    metadata:
      labels:
        app: review-database-pod
    spec:
      containers:
        - name: mysql
          image: 'ghcr.io/antje12/ba/review-database:latest'
          args:
            - '--default-authentication-plugin=mysql_native_password'
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: 100m
              memory: 400Mi
            limits:
              cpu: 200m
              memory: 600Mi
          volumeMounts:
            - name: review-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: review-persistent-storage
          persistentVolumeClaim:
            claimName: review-pv-claim
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: review-pv-claim
  labels:
    app: review-database-pod
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
