apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    -
      name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: frontend-pod
  sessionAffinity: ClientIP
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-pod
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend-pod
    spec:
      containers:
        -
          image: "ghcr.io/antje12/ba/frontend:latest"
          imagePullPolicy: Always
          name: frontend
          ports:
            -
              containerPort: 80
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          readinessProbe:
            httpGet:
              port: 80
              path: /Get
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
      imagePullSecrets:
        -
          name: regcred
