apiVersion: v1
kind: Service
metadata:
  name: job-service
spec:
  ports:
    -
      name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: job-service-pod
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-service-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: job-service-pod
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: job-service-pod
    spec:
      containers:
        -
          image: "ghcr.io/antje12/ba/job-service:{IMG_TAG}"
          imagePullPolicy: Always
          name: job-service
          ports:
            -
              containerPort: 80
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          readinessProbe:
            httpGet:
              path: /JobService/Get
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 3
      imagePullSecrets:
        -
          name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: job-database
spec:
  ports:
    -
      port: 3306
      targetPort: 3306
  selector:
    app: job-database-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-database-pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: job-database-pod
    spec:
      containers:
        -
          args:
            - "--default-authentication-plugin=mysql_native_password"
          image: "ghcr.io/antje12/ba/job-database:{IMG_TAG}"
          name: mysql
          ports:
            -
              containerPort: 3306
          resources:
            limits:
              cpu: 200m
              memory: 600Mi
            requests:
              cpu: 100m
              memory: 400Mi
          volumeMounts:
            -
              mountPath: /var/lib/mysql
              name: job-persistent-storage
      imagePullSecrets:
        -
          name: regcred
      volumes:
        -
          name: job-persistent-storage
          persistentVolumeClaim:
            claimName: job-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: job-database-pod
  name: job-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
