apiVersion: v1
kind: Service
metadata:
  name: contract-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: contract-service-pod
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contract-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contract-service-pod
  template:
    metadata:
      labels:
        app: contract-service-pod
    spec:
      containers:
      - name: contract-service
        image: ghcr.io/antje12/ba/contract-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
      imagePullSecrets:
      - name: regcred
---
  apiVersion: v1
  kind: Service
  metadata:
    name: contract-database
  spec:
    ports:
      - port: 3306
        targetPort: 3306
    selector:
      app: contract-database-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contract-database-deployment
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: contract-database-pod
  template:
    metadata:
      labels:
        app: contract-database-pod
    spec:
      containers:
        - name: mysql
          image: ghcr.io/antje12/ba/contract-database:latest
          args: ["--default-authentication-plugin=mysql_native_password"]
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: "100m"
              memory: "400Mi"
            limits:
              cpu: "200m"
              memory: "600Mi"              
          volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
      app: contract-database-pod
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
